apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prometheus-ecs-discovery.labels" . | nindent 4 }}
data:
  config.yaml: |
    cluster: {{ .Values.ecsDiscovery.cluster | quote }}
    scrape-interval: {{ .Values.ecsDiscovery.scrapeInterval | quote }}
    write-to: {{ .Values.ecsDiscovery.writeTo | quote }}
    server-name-label: {{ .Values.ecsDiscovery.serverNameLabel | quote }}
    job-name-label: {{ .Values.ecsDiscovery.jobNameLabel | quote }}
    path-label: {{ .Values.ecsDiscovery.pathLabel | quote }}
    port-label: {{ .Values.ecsDiscovery.portLabel | quote }} 