{{- if .Values.storage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "common.names.fullname" . }}-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prometheus-ecs-discovery.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.storage.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  {{- if .Values.storage.existingClaim }}
  volumeName: {{ .Values.storage.existingClaim }}
  {{- else }}
  storageClassName: {{ .Values.storage.storageClass }}
  {{- end }}
{{- end }} 